ALTER TABLE codex_ticket_attempts
    ADD COLUMN IF NOT EXISTS ticket_generation_id UUID,
    ADD COLUMN IF NOT EXISTS verification_method TEXT,
    ADD COLUMN IF NOT EXISTS fingerprint_commit TEXT,
    ADD COLUMN IF NOT EXISTS fingerprint_predicted_model TEXT,
    ADD COLUMN IF NOT EXISTS fingerprint_probability DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS fingerprint_matched BOOLEAN,
    ADD COLUMN IF NOT EXISTS challenge_expected_count INTEGER,
    ADD COLUMN IF NOT EXISTS parsed_number_count INTEGER,
    ADD COLUMN IF NOT EXISTS turn_state_present BOOLEAN,
    ADD COLUMN IF NOT EXISTS cookie_present BOOLEAN;

ALTER TABLE codex_ticket_attempts
    DROP CONSTRAINT IF EXISTS codex_ticket_attempts_source_check;
ALTER TABLE codex_ticket_attempts
    ADD CONSTRAINT codex_ticket_attempts_source_check
    CHECK (source IN ('automatic', 'manual', 'diagnostic'));
ALTER TABLE codex_ticket_attempts
    ADD CONSTRAINT codex_ticket_attempts_probability_check
    CHECK (fingerprint_probability IS NULL OR fingerprint_probability BETWEEN 0 AND 1);

CREATE UNIQUE INDEX IF NOT EXISTS codex_ticket_attempts_success_generation
    ON codex_ticket_attempts_success (ticket_generation_id)
    WHERE ticket_generation_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS codex_ticket_attempts_success_cleanup
    ON codex_ticket_attempts_success (occurred_at, id);
CREATE INDEX IF NOT EXISTS codex_ticket_attempts_account_time
    ON codex_ticket_attempts (account_id, occurred_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS codex_ticket_invalidations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    model TEXT NOT NULL,
    ticket_generation_id UUID NOT NULL UNIQUE,
    occurred_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reason_code TEXT NOT NULL CHECK (reason_code = 'upstream_new_turn_state'),
    response_http_status INTEGER,
    request_kind TEXT NOT NULL CHECK (request_kind IN ('user_request', 'diagnostic')),
    request_route TEXT NOT NULL,
    invalidated_current BOOLEAN NOT NULL,
    original_ticket TEXT,
    original_cookie TEXT,
    returned_ticket TEXT NOT NULL,
    returned_cookie TEXT,
    returned_set_cookies JSONB,
    CONSTRAINT codex_ticket_invalidations_cookies_array_check
        CHECK (returned_set_cookies IS NULL OR jsonb_typeof(returned_set_cookies) = 'array')
);
CREATE INDEX IF NOT EXISTS codex_ticket_invalidations_account_time
    ON codex_ticket_invalidations (account_id, occurred_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS codex_ticket_invalidations_account_model_time
    ON codex_ticket_invalidations (account_id, model, occurred_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS codex_ticket_invalidations_cleanup
    ON codex_ticket_invalidations (occurred_at, id);
