package authz

// RouteRule binds exact registered endpoints to permissions. Unlisted endpoints
// are denied. Native registrations stay intact; coverage checks this table against the real router.
type RouteRule struct {
	All, Any                                 []string
	ReadOnly                                 bool
	RequestSchema                            string
	SuperOnly, Self, Mutates, NewCredentials bool
}

func (r RouteRule) Allows(s Subject) bool {
	if s.Role == SuperAdmin {
		return true
	}
	if s.Role != Admin || r.SuperOnly {
		return false
	}
	if r.Self {
		return true
	}
	if len(r.All) == 0 && len(r.Any) == 0 {
		return false
	}
	if !s.CanAll(r.All...) {
		return false
	}
	return len(r.Any) == 0 || s.CanAny(r.Any...)
}

var routeRules = map[string]RouteRule{
	"DELETE /api/v1/admin/accounts/:id":                                                     {All: []string{"accounts.manage"}, Mutates: true},
	"DELETE /api/v1/admin/accounts/:id/ollama-cloud-usage/session":                          {All: []string{"accounts.read", "billing.cost.read", "accounts.manage", "accounts.authorize"}, Mutates: true},
	"DELETE /api/v1/admin/accounts/:id/temp-unschedulable":                                  {All: []string{"accounts.manage"}, Mutates: true},
	"DELETE /api/v1/admin/affiliates/users/:user_id":                                        {All: []string{"affiliates.manage"}, Mutates: true},
	"DELETE /api/v1/admin/announcements/:id":                                                {All: []string{"announcements.manage"}, Mutates: true},
	"DELETE /api/v1/admin/backups/:id":                                                      {SuperOnly: true, Mutates: true},
	"DELETE /api/v1/admin/channel-monitor-templates/:id":                                    {All: []string{"channel_monitor.manage"}, Mutates: true},
	"DELETE /api/v1/admin/channel-monitors/:id":                                             {All: []string{"channel_monitor.manage"}, Mutates: true},
	"DELETE /api/v1/admin/channels/:id":                                                     {All: []string{"channels.manage"}, Mutates: true},
	"DELETE /api/v1/admin/data-management/s3/profiles/:profile_id":                          {SuperOnly: true, Mutates: true},
	"DELETE /api/v1/admin/data-management/sources/:source_type/profiles/:profile_id":        {SuperOnly: true, Mutates: true},
	"DELETE /api/v1/admin/error-passthrough-rules/:id":                                      {SuperOnly: true, Mutates: true},
	"DELETE /api/v1/admin/groups/:id":                                                       {All: []string{"groups.manage"}, Mutates: true},
	"DELETE /api/v1/admin/groups/:id/composite-routes/:route_id":                            {All: []string{"groups.manage"}, Mutates: true},
	"DELETE /api/v1/admin/groups/:id/rate-multipliers":                                      {All: []string{"groups.manage", "billing.rates.update"}, Mutates: true},
	"DELETE /api/v1/admin/groups/:id/rpm-overrides":                                         {All: []string{"groups.manage"}, Mutates: true},
	"DELETE /api/v1/admin/ops/alert-rules/:id":                                              {All: []string{"ops.manage"}, Mutates: true},
	"DELETE /api/v1/admin/payment/plans/:id":                                                {All: []string{"plans.manage"}, Mutates: true},
	"DELETE /api/v1/admin/payment/providers/:id":                                            {SuperOnly: true, Mutates: true},
	"DELETE /api/v1/admin/plugins/:id":                                                      {SuperOnly: true, Mutates: true},
	"DELETE /api/v1/admin/promo-codes/:id":                                                  {All: []string{"promo_codes.manage"}, Mutates: true},
	"DELETE /api/v1/admin/prompt-audit/events/:id":                                          {SuperOnly: true, Mutates: true},
	"DELETE /api/v1/admin/proxies/:id":                                                      {All: []string{"proxies.manage"}, Mutates: true},
	"DELETE /api/v1/admin/redeem-codes/:id":                                                 {All: []string{"redeem_codes.manage"}, Mutates: true},
	"DELETE /api/v1/admin/risk-control/hashes":                                              {All: []string{"risk.manage"}, Mutates: true},
	"DELETE /api/v1/admin/risk-control/hashes/all":                                          {All: []string{"risk.manage"}, Mutates: true},
	"DELETE /api/v1/admin/scheduled-test-plans/:id":                                         {All: []string{"accounts.diagnostics"}, Mutates: true},
	"DELETE /api/v1/admin/settings/admin-api-key":                                           {SuperOnly: true, Mutates: true},
	"DELETE /api/v1/admin/subscriptions/:id":                                                {All: []string{"subscriptions.manage"}, Mutates: true},
	"DELETE /api/v1/admin/tls-fingerprint-profiles/:id":                                     {SuperOnly: true, Mutates: true},
	"DELETE /api/v1/admin/user-attributes/:id":                                              {All: []string{"users.update"}, Mutates: true},
	"DELETE /api/v1/admin/users/:id":                                                        {Any: []string{"users.delete", "staff.manage"}, Mutates: true},
	"GET /api/v1/admin/accounts":                                                            {All: []string{"accounts.read"}},
	"GET /api/v1/admin/accounts/:id":                                                        {All: []string{"accounts.read"}},
	"GET /api/v1/admin/accounts/:id/claude/reset-credits":                                   {All: []string{"accounts.read"}},
	"GET /api/v1/admin/accounts/:id/codex-diagnostic":                                       {All: []string{"accounts.diagnostics"}},
	"GET /api/v1/admin/accounts/:id/codex-diagnostic/history":                               {All: []string{"accounts.diagnostics"}},
	"GET /api/v1/admin/accounts/:id/grok-media-eligibility":                                 {All: []string{"accounts.read"}},
	"GET /api/v1/admin/accounts/:id/models":                                                 {All: []string{"accounts.read"}},
	"GET /api/v1/admin/accounts/:id/ollama-cloud-usage":                                     {All: []string{"accounts.read", "billing.cost.read"}},
	"GET /api/v1/admin/accounts/:id/opencode-go-usage":                                      {All: []string{"accounts.read", "billing.cost.read"}},
	"GET /api/v1/admin/accounts/:id/scheduled-test-plans":                                   {All: []string{"accounts.diagnostics"}},
	"GET /api/v1/admin/accounts/:id/stats":                                                  {All: []string{"accounts.read"}},
	"GET /api/v1/admin/accounts/:id/temp-unschedulable":                                     {All: []string{"accounts.read"}},
	"GET /api/v1/admin/accounts/:id/today-stats":                                            {All: []string{"accounts.read"}},
	"GET /api/v1/admin/accounts/:id/usage":                                                  {All: []string{"accounts.read"}},
	"GET /api/v1/admin/accounts/antigravity/default-model-mapping":                          {All: []string{"accounts.read"}},
	"GET /api/v1/admin/accounts/data":                                                       {SuperOnly: true, NewCredentials: true},
	"GET /api/v1/admin/accounts/ollama-cloud-usage/settings":                                {SuperOnly: true},
	"GET /api/v1/admin/accounts/opencode-go-usage/settings":                                 {SuperOnly: true},
	"GET /api/v1/admin/accounts/upstream-billing-probe/settings":                            {SuperOnly: true},
	"GET /api/v1/admin/accounts/upstream-billing-rates":                                     {All: []string{"accounts.read", "billing.cost.read"}},
	"GET /api/v1/admin/affiliates/invites":                                                  {All: []string{"affiliates.read"}},
	"GET /api/v1/admin/affiliates/rebates":                                                  {All: []string{"affiliates.read"}},
	"GET /api/v1/admin/affiliates/transfers":                                                {All: []string{"affiliates.read"}},
	"GET /api/v1/admin/affiliates/users":                                                    {All: []string{"affiliates.read"}},
	"GET /api/v1/admin/affiliates/users/:user_id/overview":                                  {All: []string{"affiliates.read"}},
	"GET /api/v1/admin/affiliates/users/lookup":                                             {All: []string{"affiliates.read"}},
	"GET /api/v1/admin/announcements":                                                       {All: []string{"announcements.read"}},
	"GET /api/v1/admin/announcements/:id":                                                   {All: []string{"announcements.read"}},
	"GET /api/v1/admin/announcements/:id/read-status":                                       {All: []string{"announcements.read"}},
	"GET /api/v1/admin/audit-logs":                                                          {All: []string{"audit.read"}},
	"GET /api/v1/admin/audit-logs/:id":                                                      {All: []string{"audit.read"}},
	"GET /api/v1/admin/backups":                                                             {SuperOnly: true},
	"GET /api/v1/admin/backups/:id":                                                         {SuperOnly: true},
	"GET /api/v1/admin/backups/:id/download-url":                                            {SuperOnly: true},
	"GET /api/v1/admin/backups/image-storage":                                               {SuperOnly: true},
	"GET /api/v1/admin/backups/s3-config":                                                   {SuperOnly: true},
	"GET /api/v1/admin/backups/schedule":                                                    {SuperOnly: true},
	"GET /api/v1/admin/channel-monitor-templates":                                           {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channel-monitor-templates/:id":                                       {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channel-monitor-templates/:id/monitors":                              {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channel-monitor-v2/config":                                           {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channel-monitor-v2/dimensions":                                       {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channel-monitor-v2/errors":                                           {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channel-monitor-v2/matrix":                                           {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channel-monitor-v2/models":                                           {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channel-monitor-v2/snapshot":                                         {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channel-monitor-v2/users":                                            {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channel-monitors":                                                    {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channel-monitors/:id":                                                {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channel-monitors/:id/history":                                        {All: []string{"channel_monitor.read"}},
	"GET /api/v1/admin/channels":                                                            {All: []string{"channels.read"}},
	"GET /api/v1/admin/channels/:id":                                                        {All: []string{"channels.read"}},
	"GET /api/v1/admin/channels/model-pricing":                                              {All: []string{"channels.read"}},
	"GET /api/v1/admin/channels/pricing/sync-models":                                        {All: []string{"channels.manage", "billing.rates.update"}, Mutates: true},
	"GET /api/v1/admin/cn-providers/accounts/:id/balance":                                   {All: []string{"accounts.read", "billing.cost.read"}},
	"GET /api/v1/admin/cn-providers/accounts/:id/quota":                                     {All: []string{"accounts.read", "billing.cost.read"}},
	"GET /api/v1/admin/compliance":                                                          {Self: true},
	"GET /api/v1/admin/dashboard/api-key-breakdown":                                         {Any: []string{"dashboard.read", "usage.read"}},
	"GET /api/v1/admin/dashboard/api-keys-trend":                                            {Any: []string{"dashboard.read", "usage.read"}},
	"GET /api/v1/admin/dashboard/groups":                                                    {Any: []string{"dashboard.read", "usage.read"}},
	"GET /api/v1/admin/dashboard/models":                                                    {Any: []string{"dashboard.read", "usage.read"}},
	"GET /api/v1/admin/dashboard/realtime":                                                  {Any: []string{"dashboard.read", "usage.read"}},
	"GET /api/v1/admin/dashboard/snapshot-v2":                                               {Any: []string{"dashboard.read", "usage.read"}},
	"GET /api/v1/admin/dashboard/stats":                                                     {Any: []string{"dashboard.read", "usage.read"}},
	"GET /api/v1/admin/dashboard/trend":                                                     {Any: []string{"dashboard.read", "usage.read"}},
	"GET /api/v1/admin/dashboard/user-breakdown":                                            {Any: []string{"dashboard.read", "usage.read"}},
	"GET /api/v1/admin/dashboard/users-ranking":                                             {Any: []string{"dashboard.read", "usage.read"}},
	"GET /api/v1/admin/dashboard/users-trend":                                               {Any: []string{"dashboard.read", "usage.read"}},
	"GET /api/v1/admin/data-management/agent/health":                                        {SuperOnly: true},
	"GET /api/v1/admin/data-management/backups":                                             {SuperOnly: true},
	"GET /api/v1/admin/data-management/backups/:job_id":                                     {SuperOnly: true},
	"GET /api/v1/admin/data-management/config":                                              {SuperOnly: true},
	"GET /api/v1/admin/data-management/s3/profiles":                                         {SuperOnly: true},
	"GET /api/v1/admin/data-management/sources/:source_type/profiles":                       {SuperOnly: true},
	"GET /api/v1/admin/error-passthrough-rules":                                             {SuperOnly: true},
	"GET /api/v1/admin/error-passthrough-rules/:id":                                         {SuperOnly: true},
	"GET /api/v1/admin/gemini/oauth/capabilities":                                           {All: []string{"accounts.read"}},
	"GET /api/v1/admin/grok/accounts/:id/quota":                                             {All: []string{"accounts.read", "billing.cost.read"}},
	"GET /api/v1/admin/grok/oauth/capabilities":                                             {All: []string{"accounts.read"}},
	"GET /api/v1/admin/grok/runtime-sanity":                                                 {SuperOnly: true},
	"GET /api/v1/admin/groups":                                                              {All: []string{"groups.read"}},
	"GET /api/v1/admin/groups/:id":                                                          {All: []string{"groups.read"}},
	"GET /api/v1/admin/groups/:id/api-keys":                                                 {All: []string{"groups.read", "api_keys.read"}},
	"GET /api/v1/admin/groups/:id/composite-routes":                                         {All: []string{"groups.read"}},
	"GET /api/v1/admin/groups/:id/model-allowlist-candidates":                               {All: []string{"groups.read"}},
	"GET /api/v1/admin/groups/:id/rate-multipliers":                                         {All: []string{"groups.read"}},
	"GET /api/v1/admin/groups/:id/stats":                                                    {All: []string{"groups.read"}},
	"GET /api/v1/admin/groups/:id/subscriptions":                                            {All: []string{"subscriptions.read"}},
	"GET /api/v1/admin/groups/all":                                                          {Any: []string{"groups.read", "users.read", "api_keys.read", "accounts.read", "usage.read", "subscriptions.read", "plans.read", "channels.read", "risk.read", "announcements.read", "redeem_codes.read"}},
	"GET /api/v1/admin/groups/capacity-summary":                                             {All: []string{"groups.read"}},
	"GET /api/v1/admin/groups/live-capability":                                              {All: []string{"groups.read"}},
	"GET /api/v1/admin/groups/usage-summary":                                                {All: []string{"groups.read"}},
	"GET /api/v1/admin/openai/accounts/:id/quota":                                           {All: []string{"accounts.read", "billing.cost.read"}},
	"GET /api/v1/admin/ops/account-availability":                                            {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/advanced-settings":                                               {SuperOnly: true},
	"GET /api/v1/admin/ops/alert-events":                                                    {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/alert-events/:id":                                                {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/alert-rules":                                                     {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/auth-cache-invalidation/health":                                  {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/concurrency":                                                     {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/dashboard/error-distribution":                                    {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/dashboard/error-trend":                                           {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/dashboard/latency-histogram":                                     {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/dashboard/openai-token-stats":                                    {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/dashboard/overview":                                              {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/dashboard/snapshot-v2":                                           {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/dashboard/throughput-trend":                                      {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/email-notification/config":                                       {SuperOnly: true},
	"GET /api/v1/admin/ops/errors":                                                          {Any: []string{"ops.read", "usage.read"}},
	"GET /api/v1/admin/ops/errors/:id":                                                      {Any: []string{"ops.read", "usage.read"}},
	"GET /api/v1/admin/ops/ingress-rejections":                                              {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/ingress-rejections/health":                                       {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/realtime-traffic":                                                {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/request-errors":                                                  {Any: []string{"ops.read", "usage.read"}},
	"GET /api/v1/admin/ops/request-errors/:id":                                              {Any: []string{"ops.read", "usage.read"}},
	"GET /api/v1/admin/ops/request-errors/:id/upstream-errors":                              {Any: []string{"ops.read", "usage.read"}},
	"GET /api/v1/admin/ops/requests":                                                        {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/runtime/alert":                                                   {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/runtime/logging":                                                 {SuperOnly: true},
	"GET /api/v1/admin/ops/settings/metric-thresholds":                                      {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/system-logs":                                                     {SuperOnly: true},
	"GET /api/v1/admin/ops/system-logs/health":                                              {SuperOnly: true},
	"GET /api/v1/admin/ops/upstream-errors":                                                 {Any: []string{"ops.read", "usage.read"}},
	"GET /api/v1/admin/ops/upstream-errors/:id":                                             {Any: []string{"ops.read", "usage.read"}},
	"GET /api/v1/admin/ops/user-concurrency":                                                {All: []string{"ops.read"}},
	"GET /api/v1/admin/ops/ws/qps":                                                          {All: []string{"ops.read"}},
	"GET /api/v1/admin/payment/config":                                                      {SuperOnly: true},
	"GET /api/v1/admin/payment/dashboard":                                                   {All: []string{"orders.read"}},
	"GET /api/v1/admin/payment/orders":                                                      {All: []string{"orders.read"}},
	"GET /api/v1/admin/payment/orders/:id":                                                  {All: []string{"orders.read"}},
	"GET /api/v1/admin/payment/plans":                                                       {All: []string{"plans.read"}},
	"GET /api/v1/admin/payment/providers":                                                   {SuperOnly: true},
	"GET /api/v1/admin/plugins":                                                             {SuperOnly: true},
	"GET /api/v1/admin/plugins/:id":                                                         {SuperOnly: true},
	"GET /api/v1/admin/plugins/:id/config":                                                  {SuperOnly: true},
	"GET /api/v1/admin/plugins/:id/status":                                                  {SuperOnly: true},
	"GET /api/v1/admin/promo-codes":                                                         {All: []string{"promo_codes.read"}},
	"GET /api/v1/admin/promo-codes/:id":                                                     {All: []string{"promo_codes.read"}},
	"GET /api/v1/admin/promo-codes/:id/usages":                                              {All: []string{"promo_codes.read"}},
	"GET /api/v1/admin/prompt-audit/config":                                                 {SuperOnly: true},
	"GET /api/v1/admin/prompt-audit/events":                                                 {All: []string{"prompt_audit.read"}},
	"GET /api/v1/admin/prompt-audit/events/:id":                                             {All: []string{"prompt_audit.content.read"}},
	"GET /api/v1/admin/prompt-audit/runtime":                                                {All: []string{"prompt_audit.read"}},
	"GET /api/v1/admin/proxies":                                                             {All: []string{"proxies.read"}},
	"GET /api/v1/admin/proxies/:id":                                                         {All: []string{"proxies.read"}},
	"GET /api/v1/admin/proxies/:id/accounts":                                                {All: []string{"proxies.read", "accounts.read"}},
	"GET /api/v1/admin/proxies/:id/stats":                                                   {All: []string{"proxies.read"}},
	"GET /api/v1/admin/proxies/all":                                                         {Any: []string{"proxies.read", "accounts.read"}},
	"GET /api/v1/admin/proxies/data":                                                        {SuperOnly: true, NewCredentials: true},
	"GET /api/v1/admin/redeem-codes":                                                        {All: []string{"redeem_codes.read"}},
	"GET /api/v1/admin/redeem-codes/:id":                                                    {All: []string{"redeem_codes.read"}},
	"GET /api/v1/admin/redeem-codes/export":                                                 {All: []string{"redeem_codes.export"}},
	"GET /api/v1/admin/redeem-codes/stats":                                                  {All: []string{"redeem_codes.read"}},
	"GET /api/v1/admin/risk-control/config":                                                 {SuperOnly: true},
	"GET /api/v1/admin/risk-control/logs":                                                   {All: []string{"risk.read"}},
	"GET /api/v1/admin/risk-control/status":                                                 {All: []string{"risk.read"}},
	"GET /api/v1/admin/roles/admin/permissions":                                             {SuperOnly: true},
	"GET /api/v1/admin/scheduled-test-plans/:id/results":                                    {All: []string{"accounts.diagnostics"}},
	"GET /api/v1/admin/settings":                                                            {Any: []string{"settings.general.read", "settings.content.read"}},
	"GET /api/v1/admin/settings/admin-api-key":                                              {SuperOnly: true, NewCredentials: true},
	"GET /api/v1/admin/settings/beta-policy":                                                {SuperOnly: true},
	"GET /api/v1/admin/settings/email-templates":                                            {All: []string{"settings.content.read"}},
	"GET /api/v1/admin/settings/email-templates/:event/:locale":                             {All: []string{"settings.content.read"}},
	"GET /api/v1/admin/settings/openai-images-oauth-unavailable-cooldown":                   {SuperOnly: true},
	"GET /api/v1/admin/settings/overload-cooldown":                                          {SuperOnly: true},
	"GET /api/v1/admin/settings/panel-rate-limit":                                           {SuperOnly: true},
	"GET /api/v1/admin/settings/rate-limit-429-cooldown":                                    {SuperOnly: true},
	"GET /api/v1/admin/settings/rectifier":                                                  {SuperOnly: true},
	"GET /api/v1/admin/settings/stream-timeout":                                             {SuperOnly: true},
	"GET /api/v1/admin/settings/web-search-emulation":                                       {SuperOnly: true},
	"GET /api/v1/admin/subscriptions":                                                       {All: []string{"subscriptions.read"}},
	"GET /api/v1/admin/subscriptions/:id":                                                   {All: []string{"subscriptions.read"}},
	"GET /api/v1/admin/subscriptions/:id/progress":                                          {All: []string{"subscriptions.read"}},
	"GET /api/v1/admin/system/check-updates":                                                {SuperOnly: true},
	"GET /api/v1/admin/system/rollback-versions":                                            {SuperOnly: true},
	"GET /api/v1/admin/system/version":                                                      {SuperOnly: true},
	"GET /api/v1/admin/tls-fingerprint-profiles":                                            {SuperOnly: true},
	"GET /api/v1/admin/tls-fingerprint-profiles/:id":                                        {SuperOnly: true},
	"GET /api/v1/admin/usage":                                                               {All: []string{"usage.read"}},
	"GET /api/v1/admin/usage/cleanup-tasks":                                                 {SuperOnly: true},
	"GET /api/v1/admin/usage/search-api-keys":                                               {All: []string{"usage.read"}},
	"GET /api/v1/admin/usage/search-users":                                                  {All: []string{"usage.read"}},
	"GET /api/v1/admin/usage/stats":                                                         {All: []string{"usage.read"}},
	"GET /api/v1/admin/user-attributes":                                                     {All: []string{"users.read"}},
	"GET /api/v1/admin/users":                                                               {All: []string{"users.read"}},
	"GET /api/v1/admin/users/:id":                                                           {All: []string{"users.read"}},
	"GET /api/v1/admin/users/:id/api-keys":                                                  {All: []string{"users.read", "api_keys.read"}},
	"GET /api/v1/admin/users/:id/attributes":                                                {All: []string{"users.read"}},
	"GET /api/v1/admin/users/:id/balance-history":                                           {All: []string{"users.read"}},
	"GET /api/v1/admin/users/:id/platform-quotas":                                           {All: []string{"users.read"}},
	"GET /api/v1/admin/users/:id/rpm-status":                                                {All: []string{"users.read"}},
	"GET /api/v1/admin/users/:id/subscriptions":                                             {All: []string{"subscriptions.read"}},
	"GET /api/v1/admin/users/:id/usage":                                                     {All: []string{"usage.read"}},
	"GET /api/v1/pages":                                                                     {SuperOnly: true},
	"POST /api/v1/admin/accounts":                                                           {All: []string{"accounts.authorize"}, Mutates: true, RequestSchema: "account.create"},
	"POST /api/v1/admin/accounts/:id/apply-oauth-credentials":                               {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/claude/reset-credits/redeem":                           {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/clear-error":                                           {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/clear-rate-limit":                                      {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/codex-diagnostic":                                      {All: []string{"accounts.diagnostics"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/codex-diagnostic/:run_id/cancel":                       {All: []string{"accounts.diagnostics"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/duplicate":                                             {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/models/sync-upstream":                                  {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/ollama-cloud-usage/refresh":                            {All: []string{"accounts.read", "billing.cost.read", "accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/opencode-go-usage/refresh":                             {All: []string{"accounts.read", "billing.cost.read", "accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/recover-state":                                         {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/refresh":                                               {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/refresh-tier":                                          {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/reset-quota":                                           {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/revert-proxy-fallback":                                 {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/accounts/:id/schedulable":                                           {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/set-privacy":                                           {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/shadow":                                                {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/test":                                                  {All: []string{"accounts.diagnostics"}, Mutates: true},
	"POST /api/v1/admin/accounts/:id/upstream-billing-probe":                                {All: []string{"accounts.read", "billing.cost.read", "accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/batch":                                                     {All: []string{"accounts.authorize"}, Mutates: true, RequestSchema: "account.batch"},
	"POST /api/v1/admin/accounts/batch-clear-error":                                         {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/batch-delete":                                              {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/batch-refresh":                                             {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/batch-refresh-tier":                                        {All: []string{"accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/batch-update-credentials":                                  {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/accounts/bulk-update":                                               {All: []string{"accounts.manage"}, Mutates: true, RequestSchema: "account.bulk"},
	"POST /api/v1/admin/accounts/check-mixed-channel":                                       {All: []string{"accounts.read"}, ReadOnly: true},
	"POST /api/v1/admin/accounts/codex-diagnostic-fingerprint/refresh":                      {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/accounts/cookie-auth":                                               {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/accounts/data":                                                      {All: []string{"accounts.authorize"}, Mutates: true, RequestSchema: "account.import"},
	"POST /api/v1/admin/accounts/exchange-code":                                             {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/accounts/exchange-setup-token-code":                                 {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/accounts/generate-auth-url":                                         {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/accounts/generate-setup-token-url":                                  {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/accounts/import/codex-session":                                      {All: []string{"accounts.authorize"}, Mutates: true, RequestSchema: "account.codex"},
	"POST /api/v1/admin/accounts/models/sync-upstream-preview":                              {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/accounts/setup-token-cookie-auth":                                   {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/accounts/sync/crs":                                                  {All: []string{"accounts.authorize", "proxies.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/sync/crs/preview":                                          {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/accounts/today-stats/batch":                                         {All: []string{"accounts.read"}, ReadOnly: true},
	"POST /api/v1/admin/accounts/upstream-billing-probe/batch":                              {All: []string{"accounts.read", "billing.cost.read", "accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/accounts/usage/batch":                                               {All: []string{"accounts.read"}, ReadOnly: true},
	"POST /api/v1/admin/affiliates/users/:user_id/withdraw":                                 {All: []string{"affiliates.adjust"}, Mutates: true},
	"POST /api/v1/admin/affiliates/users/batch-rate":                                        {All: []string{"affiliates.manage"}, Mutates: true},
	"POST /api/v1/admin/announcements":                                                      {All: []string{"announcements.manage"}, Mutates: true},
	"POST /api/v1/admin/antigravity/oauth/auth-url":                                         {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/antigravity/oauth/exchange-code":                                    {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/antigravity/oauth/refresh-token":                                    {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/audit-logs/clear":                                                   {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/backups":                                                            {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/backups/:id/restore":                                                {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/backups/image-storage/test":                                         {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/backups/s3-config/test":                                             {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/channel-monitor-templates":                                          {All: []string{"channel_monitor.manage"}, Mutates: true},
	"POST /api/v1/admin/channel-monitor-templates/:id/apply":                                {All: []string{"channel_monitor.manage"}, Mutates: true},
	"POST /api/v1/admin/channel-monitors":                                                   {All: []string{"channel_monitor.manage"}, Mutates: true},
	"POST /api/v1/admin/channel-monitors/:id/duplicate":                                     {All: []string{"channel_monitor.manage"}, Mutates: true},
	"POST /api/v1/admin/channel-monitors/:id/run":                                           {All: []string{"channel_monitor.manage"}, Mutates: true},
	"POST /api/v1/admin/channels":                                                           {All: []string{"channels.manage"}, Mutates: true, RequestSchema: "channel.create"},
	"POST /api/v1/admin/compliance/accept":                                                  {Self: true, Mutates: true},
	"POST /api/v1/admin/dashboard/aggregation/backfill":                                     {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/dashboard/api-keys-usage":                                           {Any: []string{"dashboard.read", "usage.read", "api_keys.read"}, ReadOnly: true},
	"POST /api/v1/admin/dashboard/users-usage":                                              {Any: []string{"dashboard.read", "usage.read", "users.read"}, ReadOnly: true},
	"POST /api/v1/admin/data-management/backups":                                            {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/data-management/s3/profiles":                                        {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/data-management/s3/profiles/:profile_id/activate":                   {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/data-management/s3/test":                                            {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/data-management/sources/:source_type/profiles":                      {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/data-management/sources/:source_type/profiles/:profile_id/activate": {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/error-passthrough-rules":                                            {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/gemini/oauth/auth-url":                                              {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/gemini/oauth/exchange-code":                                         {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/grok/accounts/:id/refresh":                                          {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/grok/accounts/:id/reset-quota":                                      {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/grok/oauth/auth-url":                                                {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/grok/oauth/create-from-oauth":                                       {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/grok/oauth/exchange-code":                                           {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/grok/oauth/password":                                                {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/grok/oauth/reconcile":                                               {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/grok/oauth/refresh-token":                                           {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/grok/oauth/sso-token":                                               {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/grok/sso-to-oauth":                                                  {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true, RequestSchema: "account.sso"},
	"POST /api/v1/admin/groups":                                                             {All: []string{"groups.manage"}, Mutates: true, RequestSchema: "group.create"},
	"POST /api/v1/admin/groups/:id/composite-routes":                                        {All: []string{"groups.manage"}, Mutates: true},
	"POST /api/v1/admin/groups/:id/composite-routes/preview":                                {All: []string{"groups.read"}, ReadOnly: true},
	"POST /api/v1/admin/groups/:id/duplicate":                                               {All: []string{"groups.manage"}, Mutates: true},
	"POST /api/v1/admin/openai/accounts/:id/quota/refresh":                                  {All: []string{"accounts.read", "billing.cost.read", "accounts.manage"}, Mutates: true},
	"POST /api/v1/admin/openai/accounts/:id/referrals/invite":                               {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/openai/accounts/:id/referrals/refresh":                              {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/openai/accounts/:id/refresh":                                        {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/openai/accounts/:id/reset-quota":                                    {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/openai/create-from-codex-pat":                                       {All: []string{"accounts.authorize"}, Mutates: true, RequestSchema: "account.pat"},
	"POST /api/v1/admin/openai/create-from-oauth":                                           {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/openai/exchange-code":                                               {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/openai/generate-auth-url":                                           {All: []string{"accounts.authorize"}, Mutates: true},
	"POST /api/v1/admin/openai/refresh-token":                                               {All: []string{"accounts.authorize"}, Mutates: true, NewCredentials: true},
	"POST /api/v1/admin/ops/alert-rules":                                                    {All: []string{"ops.manage"}, Mutates: true},
	"POST /api/v1/admin/ops/alert-silences":                                                 {All: []string{"ops.manage"}, Mutates: true},
	"POST /api/v1/admin/ops/runtime/logging/reset":                                          {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/ops/system-logs/cleanup":                                            {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/payment/orders/:id/cancel":                                          {All: []string{"orders.manage"}, Mutates: true},
	"POST /api/v1/admin/payment/orders/:id/refund":                                          {All: []string{"orders.refund"}, Mutates: true},
	"POST /api/v1/admin/payment/orders/:id/refund/query":                                    {All: []string{"orders.refund"}, Mutates: true},
	"POST /api/v1/admin/payment/orders/:id/refund/resolve":                                  {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/payment/orders/:id/retry":                                           {All: []string{"orders.manage"}, Mutates: true},
	"POST /api/v1/admin/payment/plans":                                                      {All: []string{"plans.manage"}, Mutates: true, RequestSchema: "plan.create"},
	"POST /api/v1/admin/payment/providers":                                                  {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/plugins/:id/disable":                                                {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/plugins/:id/enable":                                                 {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/plugins/:id/test":                                                   {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/plugins/:id/ui-session":                                             {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/plugins/upload":                                                     {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/promo-codes":                                                        {All: []string{"promo_codes.manage"}, Mutates: true},
	"POST /api/v1/admin/prompt-audit/endpoints/probe":                                       {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/prompt-audit/events/batch-delete":                                   {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/prompt-audit/events/delete-by-filter":                               {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/prompt-audit/events/delete-preview":                                 {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/proxies":                                                            {All: []string{"proxies.manage"}, Mutates: true},
	"POST /api/v1/admin/proxies/:id/quality-check":                                          {All: []string{"proxies.manage"}, Mutates: true},
	"POST /api/v1/admin/proxies/:id/test":                                                   {All: []string{"proxies.manage"}, Mutates: true},
	"POST /api/v1/admin/proxies/batch":                                                      {All: []string{"proxies.manage"}, Mutates: true},
	"POST /api/v1/admin/proxies/batch-delete":                                               {All: []string{"proxies.manage"}, Mutates: true},
	"POST /api/v1/admin/proxies/data":                                                       {All: []string{"proxies.manage"}, Mutates: true},
	"POST /api/v1/admin/redeem-codes/:id/expire":                                            {All: []string{"redeem_codes.manage"}, Mutates: true},
	"POST /api/v1/admin/redeem-codes/batch-delete":                                          {All: []string{"redeem_codes.manage"}, Mutates: true},
	"POST /api/v1/admin/redeem-codes/batch-update":                                          {All: []string{"redeem_codes.manage"}, Mutates: true},
	"POST /api/v1/admin/redeem-codes/create-and-redeem":                                     {All: []string{"redeem_codes.manage", "billing.balance.adjust"}, Mutates: true},
	"POST /api/v1/admin/redeem-codes/generate":                                              {All: []string{"redeem_codes.manage"}, Mutates: true},
	"POST /api/v1/admin/risk-control/api-keys/test":                                         {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/risk-control/users/:user_id/unban":                                  {All: []string{"risk.manage"}, Mutates: true},
	"POST /api/v1/admin/scheduled-test-plans":                                               {All: []string{"accounts.diagnostics"}, Mutates: true},
	"POST /api/v1/admin/settings/admin-api-key/regenerate":                                  {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/settings/email-template-preview":                                    {All: []string{"settings.content.read"}, ReadOnly: true},
	"POST /api/v1/admin/settings/email-templates/:event/:locale/restore-official":           {All: []string{"settings.content.manage"}, Mutates: true},
	"POST /api/v1/admin/settings/send-test-email":                                           {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/settings/test-smtp":                                                 {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/settings/web-search-emulation/reset-usage":                          {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/settings/web-search-emulation/test":                                 {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/subscriptions/:id/extend":                                           {All: []string{"subscriptions.manage"}, Mutates: true},
	"POST /api/v1/admin/subscriptions/:id/reset-quota":                                      {All: []string{"subscriptions.manage"}, Mutates: true},
	"POST /api/v1/admin/subscriptions/:id/restore":                                          {All: []string{"subscriptions.manage"}, Mutates: true},
	"POST /api/v1/admin/subscriptions/:id/revoke":                                           {All: []string{"subscriptions.manage"}, Mutates: true},
	"POST /api/v1/admin/subscriptions/assign":                                               {All: []string{"subscriptions.manage"}, Mutates: true},
	"POST /api/v1/admin/subscriptions/bulk-action":                                          {All: []string{"subscriptions.manage"}, Mutates: true},
	"POST /api/v1/admin/subscriptions/bulk-assign":                                          {All: []string{"subscriptions.manage"}, Mutates: true},
	"POST /api/v1/admin/system/restart":                                                     {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/system/rollback":                                                    {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/system/update":                                                      {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/tls-fingerprint-profiles":                                           {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/usage/cleanup-tasks":                                                {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/usage/cleanup-tasks/:id/cancel":                                     {SuperOnly: true, Mutates: true},
	"POST /api/v1/admin/user-attributes":                                                    {All: []string{"users.update"}, Mutates: true},
	"POST /api/v1/admin/user-attributes/batch":                                              {All: []string{"users.read"}, ReadOnly: true},
	"POST /api/v1/admin/users":                                                              {Any: []string{"users.create", "staff.manage"}, Mutates: true},
	"POST /api/v1/admin/users/:id/auth-identities":                                          {Any: []string{"users.security", "staff.manage"}, Mutates: true},
	"POST /api/v1/admin/users/:id/balance":                                                  {All: []string{"billing.balance.adjust"}, Mutates: true},
	"POST /api/v1/admin/users/:id/platform-quotas/reset":                                    {Any: []string{"users.update", "staff.manage"}, Mutates: true},
	"POST /api/v1/admin/users/:id/replace-group":                                            {Any: []string{"users.update", "staff.manage"}, Mutates: true},
	"POST /api/v1/admin/users/batch-concurrency":                                            {Any: []string{"users.update", "staff.manage"}, Mutates: true},
	"POST /api/v1/admin/users/batch-delete":                                                 {Any: []string{"users.delete", "staff.manage"}, Mutates: true},
	"POST /api/v1/admin/users/batch-limits":                                                 {Any: []string{"users.update", "staff.manage"}, Mutates: true},
	"PUT /api/v1/admin/accounts/:id":                                                        {All: []string{"accounts.manage"}, Mutates: true, RequestSchema: "account.update"},
	"PUT /api/v1/admin/accounts/:id/codex-diagnostic":                                       {All: []string{"accounts.diagnostics"}, Mutates: true},
	"PUT /api/v1/admin/accounts/:id/grok-media-eligibility":                                 {All: []string{"accounts.manage"}, Mutates: true},
	"PUT /api/v1/admin/accounts/:id/ollama-cloud-usage/auto-refresh":                        {All: []string{"accounts.read", "billing.cost.read", "accounts.manage"}, Mutates: true},
	"PUT /api/v1/admin/accounts/:id/ollama-cloud-usage/session":                             {All: []string{"accounts.read", "billing.cost.read", "accounts.manage", "accounts.authorize"}, Mutates: true},
	"PUT /api/v1/admin/accounts/:id/opencode-go-usage/auto-refresh":                         {All: []string{"accounts.read", "billing.cost.read", "accounts.manage"}, Mutates: true},
	"PUT /api/v1/admin/accounts/:id/upstream-billing-probe":                                 {All: []string{"accounts.read", "billing.cost.read", "accounts.manage"}, Mutates: true},
	"PUT /api/v1/admin/accounts/ollama-cloud-usage/settings":                                {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/accounts/opencode-go-usage/settings":                                 {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/accounts/upstream-billing-probe/settings":                            {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/affiliates/users/:user_id":                                           {All: []string{"affiliates.manage"}, Mutates: true},
	"PUT /api/v1/admin/announcements/:id":                                                   {All: []string{"announcements.manage"}, Mutates: true},
	"PUT /api/v1/admin/api-keys/:id":                                                        {All: []string{"api_keys.manage"}, Mutates: true},
	"PUT /api/v1/admin/backups/image-storage":                                               {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/backups/s3-config":                                                   {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/backups/schedule":                                                    {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/channel-monitor-templates/:id":                                       {All: []string{"channel_monitor.manage"}, Mutates: true},
	"PUT /api/v1/admin/channel-monitor-v2/config":                                           {All: []string{"channel_monitor.manage"}, Mutates: true},
	"PUT /api/v1/admin/channel-monitors/:id":                                                {All: []string{"channel_monitor.manage"}, Mutates: true},
	"PUT /api/v1/admin/channels/:id":                                                        {All: []string{"channels.manage"}, Mutates: true, RequestSchema: "channel.update"},
	"PUT /api/v1/admin/data-management/config":                                              {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/data-management/s3/profiles/:profile_id":                             {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/data-management/sources/:source_type/profiles/:profile_id":           {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/error-passthrough-rules/:id":                                         {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/groups/:id":                                                          {All: []string{"groups.manage"}, Mutates: true, RequestSchema: "group.update"},
	"PUT /api/v1/admin/groups/:id/composite-routes/:route_id":                               {All: []string{"groups.manage"}, Mutates: true},
	"PUT /api/v1/admin/groups/:id/rate-multipliers":                                         {All: []string{"groups.manage", "billing.rates.update"}, Mutates: true},
	"PUT /api/v1/admin/groups/:id/rpm-overrides":                                            {All: []string{"groups.manage"}, Mutates: true},
	"PUT /api/v1/admin/groups/sort-order":                                                   {All: []string{"groups.manage"}, Mutates: true},
	"PUT /api/v1/admin/ops/advanced-settings":                                               {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/ops/alert-events/:id/status":                                         {All: []string{"ops.manage"}, Mutates: true},
	"PUT /api/v1/admin/ops/alert-rules/:id":                                                 {All: []string{"ops.manage"}, Mutates: true},
	"PUT /api/v1/admin/ops/email-notification/config":                                       {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/ops/errors/:id/resolve":                                              {All: []string{"ops.manage"}, Mutates: true},
	"PUT /api/v1/admin/ops/request-errors/:id/resolve":                                      {All: []string{"ops.manage"}, Mutates: true},
	"PUT /api/v1/admin/ops/runtime/alert":                                                   {All: []string{"ops.manage"}, Mutates: true},
	"PUT /api/v1/admin/ops/runtime/logging":                                                 {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/ops/settings/metric-thresholds":                                      {All: []string{"ops.manage"}, Mutates: true},
	"PUT /api/v1/admin/ops/upstream-errors/:id/resolve":                                     {All: []string{"ops.manage"}, Mutates: true},
	"PUT /api/v1/admin/payment/config":                                                      {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/payment/plans/:id":                                                   {All: []string{"plans.manage"}, Mutates: true, RequestSchema: "plan.update"},
	"PUT /api/v1/admin/payment/providers/:id":                                               {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/plugins/:id/config":                                                  {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/promo-codes/:id":                                                     {All: []string{"promo_codes.manage"}, Mutates: true},
	"PUT /api/v1/admin/prompt-audit/config":                                                 {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/proxies/:id":                                                         {All: []string{"proxies.manage"}, Mutates: true},
	"PUT /api/v1/admin/risk-control/config":                                                 {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/roles/admin/permissions":                                             {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/scheduled-test-plans/:id":                                            {All: []string{"accounts.diagnostics"}, Mutates: true},
	"PUT /api/v1/admin/settings":                                                            {Any: []string{"settings.general.manage", "settings.content.manage"}, Mutates: true},
	"PUT /api/v1/admin/settings/beta-policy":                                                {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/settings/email-templates/:event/:locale":                             {All: []string{"settings.content.manage"}, Mutates: true},
	"PUT /api/v1/admin/settings/openai-images-oauth-unavailable-cooldown":                   {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/settings/overload-cooldown":                                          {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/settings/panel-rate-limit":                                           {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/settings/rate-limit-429-cooldown":                                    {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/settings/rectifier":                                                  {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/settings/stream-timeout":                                             {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/settings/web-search-emulation":                                       {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/tls-fingerprint-profiles/:id":                                        {SuperOnly: true, Mutates: true},
	"PUT /api/v1/admin/user-attributes/:id":                                                 {All: []string{"users.update"}, Mutates: true},
	"PUT /api/v1/admin/user-attributes/reorder":                                             {All: []string{"users.update"}, Mutates: true},
	"PUT /api/v1/admin/users/:id":                                                           {Any: []string{"users.update", "staff.manage"}, Mutates: true},
	"PUT /api/v1/admin/users/:id/attributes":                                                {Any: []string{"users.update", "staff.manage"}, Mutates: true},
	"PUT /api/v1/admin/users/:id/platform-quotas":                                           {Any: []string{"users.update", "staff.manage"}, Mutates: true},
}

func RuleFor(method, path string) (RouteRule, bool) {
	rule, ok := routeRules[method+" "+path]
	return rule, ok
}
func DeclaredRoutes() map[string]RouteRule {
	out := make(map[string]RouteRule, len(routeRules))
	for key, value := range routeRules {
		out[key] = value
	}
	return out
}
